export let nidfield = [
    {
      col: "4",
      id: "nationalId",
      type: "number",
      maxLength: "40",
      title: "NID Number",
      isMandatory: true,
      placeholder: "Enter NID Number",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "name",
      type: "text",
      maxLength: "40",
      title: "Full Name Bangla",
      isMandatory: true,
      placeholder: "Enter Full Name Bangla",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "nameEn",
      type: "text",
      maxLength: "40",
      title: "Full Name English",
      isMandatory: true,
      placeholder: "Enter Full Name English",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "dateOfBirth",
      type: "text",
      maxLength: "40",
      title: "Date of Birth",
      isMandatory: true,
      placeholder: "Enter Date of Birth",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "father",
      type: "text",
      maxLength: "40",
      title: "Father Name",
      isMandatory: true,
      placeholder: "Enter Father Name",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "mother",
      type: "text",
      maxLength: "40",
      title: "Mother Name",
      isMandatory: true,
      placeholder: "Enter  Mother Name",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "gender",
      type: "text",
      maxLength: "40",
      title: "Gender",
      isMandatory: true,
      placeholder: "Enter Gender",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "spouse",
      type: "text",
      maxLength: "40",
      title: "Spouse Name",
      isMandatory: false,
      placeholder: "Enter Spouse Name",
      val: "",
      disable: false,
    },
    {
      col: "4",
      id: "occupation",
      type: "text",
      maxLength: "40",
      title: "Profession",
      isMandatory: true,
      placeholder: "Enter Profession",
      val: "",
      disable: false,
    }
  ]
  export let presentAddressData = [
    {
      col: "4",
      id: "division",
      type: "text",
      maxLength: "40",
      title: "Division",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      id: "district",
      type: "text",
      maxLength: "40",
      title: "District",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      id: "upozila",
      type: "text",
      maxLength: "40",
      title: "Upozila",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      type: "text",
      maxLength: "40",
      id: "cityCorporationOrMunicipality",
      title: "City/Municipality",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      id: "unionOrWard",
      type: "text",
      maxLength: "40",
      title: "Union/Ward",
      isMandatory: false,
      val: "32 No Ward",
      disable: false
    },
    {
      col: "4",
      id: "postOffice",
      type: "text",
      maxLength: "40",
      title: "Post Office",
      isMandatory: true,
      placeholder: "Enter Post Office",
      val: "Rampura",
      disable: false
    },
    {
      col: "4",
      id: "postalCode",
      type: "number",
      maxLength: "40",
      title: "Postal Code",
      isMandatory: false,
      placeholder: "Enter Postal Code",
      val: "1219",
      disable: false
    },
    {
      col: "4",
      id: "additionalMouzaOrMoholla",
      type: "text",
      maxLength: "40",
      title: "Mouza/Moholla",
      isMandatory: false,
      placeholder: "Enter Mouza/Moholla",
      val: "Moulvirtek Khilgong",
      disable: false
    },
    {
      col: "4",
      id: "additionalVillageOrRoad",
      type: "text",
      maxLength: "40",
      title: "Village/Road",
      isMandatory: true,
      placeholder: "Enter Village/Road",
      val: "Road No 32",
      disable: false
    },
    {
      col: "4",
      id: "homeOrHoldingNo",
      type: "text",
      maxLength: "40",
      title: "House/Holding No",
      isMandatory: true,
      placeholder: "Enter House/Holding No",
      val: "House no 1",
      disable: false
    }
  ]
  export let parmanentAddressData = [
    {
      col: "4",
      id: "division",
      type: "text",
      maxLength: "40",
      title: "Division",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      id: "district",
      type: "text",
      maxLength: "40",
      title: "District",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      id: "upozila",
      type: "text",
      maxLength: "40",
      title: "Upozila",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      type: "text",
      maxLength: "40",
      id: "cityCorporationOrMunicipality",
      title: "City/Municipality",
      isMandatory: true,
      val: "Dhaka",
      disable: false
    },
    {
      col: "4",
      id: "unionOrWard",
      type: "text",
      maxLength: "40",
      title: "Union/Ward",
      isMandatory: false,
      val: "32 No Ward",
      disable: false
    },
    {
      col: "4",
      id: "postOffice",
      type: "text",
      maxLength: "40",
      title: "Post Office",
      isMandatory: true,
      placeholder: "Enter Post Office",
      val: "Rampura",
      disable: false
    },
    {
      col: "4",
      id: "postalCode",
      type: "number",
      maxLength: "40",
      title: "Postal Code",
      isMandatory: false,
      placeholder: "Enter Postal Code",
      val: "1219",
      disable: false
    },
    {
      col: "4",
      id: "additionalMouzaOrMoholla",
      type: "text",
      maxLength: "40",
      title: "Mouza/Moholla",
      isMandatory: false,
      placeholder: "Enter Mouza/Moholla",
      val: "Moulvirtek Khilgong",
      disable: false
    },
    {
      col: "4",
      id: "additionalVillageOrRoad",
      type: "text",
      maxLength: "40",
      title: "Village/Road",
      isMandatory: true,
      placeholder: "Enter Village/Road",
      val: "Road No 32",
      disable: false
    },
    {
      col: "4",
      id: "homeOrHoldingNo",
      type: "text",
      maxLength: "40",
      title: "House/Holding No",
      isMandatory: true,
      placeholder: "Enter House/Holding No",
      val: "House no 1",
      disable: false
    }
  ]